### ISSUE TITLE
2 tests fail

### ISSUE THREAD

**Issue by grigio** [trusttoken/trueUSD#2]
Hi, just tried the tests with `./node_modules/.bin/solidity-coverage`.. is needed some more configuration with Ganache or Web3?

```
185 passing (2m)
  2 failing

  1) Contract: TokenWithFees "before each" hook:
     Error: Contract transaction couldn't be found after 50 blocks
      at /home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/web3/lib/web3/contract.js:112:1
      at /home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/web3/lib/web3/filter.js:128:1
      at Array.forEach (<anonymous>)
      at /home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/web3/lib/web3/filter.js:127:1
      at Array.forEach (<anonymous>)
      at Object.onMessage [as callback] (/home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/web3/lib/web3/filter.js:125:1)
      at /home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:259:1
      at Array.forEach (<anonymous>)
      at /home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:258:10
      at /home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

  2) Contract: TokenWithFees "before each" hook:
     Error: Contract transaction couldn't be found after 50 blocks
      at /home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/web3/lib/web3/contract.js:112:1
      at /home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/web3/lib/web3/filter.js:128:1
      at Array.forEach (<anonymous>)
      at /home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/web3/lib/web3/filter.js:127:1
      at Array.forEach (<anonymous>)
      at Object.onMessage [as callback] (/home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/web3/lib/web3/filter.js:125:1)
      at /home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:259:1
      at Array.forEach (<anonymous>)
      at /home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:258:10
      at /home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/home/grigio/Code/testing/trueUSD/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1106:12)
      at process._tickCallback (internal/process/next_tick.js:178:19)

```

**Comment by terryli0095** [comment]
unable to reproduce
